### ISSUE TITLE
Incluir área de canais de Desenvolvimento Full-Stack.

### ISSUE THREAD

**Issue by doougui** [carolcodes/youtube-br-desenvolvimento#100]
Percebi que muitos dos canais adicionados na lista são de Desenvolvimento Full-Stack, e como não há uma categoria para isso, acabam sendo adicionados ou em Back-End, ou em Front-End. Que tal criar uma categoria de Desenvolvimento Full-Stack? Acredito que assim a lista ficará mais organizada.

**Comment by doougui** [comment]
Entendi o seu ponto. No caso um canal é adicionado em uma categoria pelo seu "maior foco" (Back ou Front). Realmente criar uma categoria só para Full-Stack pode bagunçar um pouco as coisas, visto que a maior parte dos canais tem um foco maior no Back End ou no Front End.

PS: Na parte em que eu mencionei "muitos dos canais" eu levei em consideração aqueles canais que falam um pouco sobre Back-End mas o foco é Front-End (ou vice-versa).

**Comment by lucasgomide** [comment]
Exatamente. 
Eu gostei da sua ideia de criar um categoria nova, mas acho que ainda não temos uma quantidade significativa que valha a alteração agora. Mas vou ficar de olho nas próximas PRs, acredito que em breve teremos uma categoria de FullStack!

Valeu @doougui, forte abraço (:

**Comment by doougui** [comment]
Tudo bem. Forte abraço @lucasgomide (:
