### ISSUE TITLE
Adicionar streamers ou criar um repo separado e linkar aqui

### ISSUE THREAD

**Issue by ffernandorl** [carolcodes/youtube-br-desenvolvimento#124]
Primeiramente, parabéns a todos pela criação desse repositório.

Estive pensando que apesar de ser um repositório focado no youtube, vide o nome, cada vez mais vejo programadores streamando, tanto no youtube como em outras plataformas como a twitch. 

Então acredito que seria uma boa criar uma sessão para streamers, ou mesmo criar um outro repositório focado nisso e só linkar eles mutuamente.

**Comment by lucasgomide** [comment]
Olá @ffernandorl você pode enviar uma PR com a sua sugestão. Só tem um ponto, que se não me engano, para evitar que a categorização fique uma bagunça cada categoria precisa ter pelo menos 3 links. Então essa sua nova sugestão de *Streaming* precisa ter pelo menos 3 links. 

Uma outra alternativa é adicionar os canais que vc conhece que fazem streaming em outras categorias, e quando atingir a quantidade miníma vc pode mandar uma nova PR migrando os links para uma nova categoria.
