### ISSUE TITLE
Melhorar visualização mobile.

### ISSUE THREAD

**Issue by nfo94** [carolcodes/youtube-br-desenvolvimento#73]
Pessoal, no mobile o foguete está quebrando a lista:

![screenshot_2018-12-27-15-21-06](https://user-images.githubusercontent.com/24434214/50512761-9262aa80-0a72-11e9-9cb5-4165028bee86.png)

Vale a pena manter o foguete aí?
@lucasgomide @glaucia86

**Comment by lucasgomide** [comment]
Oi @nfo94 ficou bem zuado no mobile. Estou super ok em tirar, ou não mostrar apenas no mobile.

**Comment by glaucia86** [comment]
@lucasgomide concordo com o Lucas. Podem tirar.

**Comment by carolcodes** [comment]
oi pessoal, eu achei maneiro.
que tal se não mostrar apenas no mobile?

@glaucia86 @lucasgomide

**Comment by lucasgomide** [comment]
@carolcodes Eu dei sugeri isso também, estou ok com qualquer uma das opções. Embora só mostrar no desktop ficaria melhor 👍

**Comment by glaucia86** [comment]
@lucasgomide e @carolcodes já decidiram? Mantem para desktop e remove para mobile? Ou simplesmente remove do README.md?

**Comment by lucasgomide** [comment]
Estava aguardando ansiosamente pela sua PR @glaucia86 hahaha
mas acho melhor melhor apenas no desktop (: acredito que a Carol concorde tb, pq ela também sugeriu isto..

forte abraço

**Comment by glaucia86** [comment]
> Estava aguardando ansiosamente pela sua PR @glaucia86 hahaha
> mas acho melhor melhor apenas no desktop (: acredito que a Carol concorde tb, pq ela também sugeriu isto..
> 
> forte abraço

kkk blz. Vamos esperar a resposta final da @carolcodes. Assim que tiver... abro uma nova branch com a escolha dela. Abraços @lucasgomide :D

**Comment by glaucia86** [comment]
@lucasgomide e @carolcodes 

iPhone 
![image](https://user-images.githubusercontent.com/1631477/50530900-9a116600-0ae9-11e9-9db3-7a4b4e522118.png)

**Comment by glaucia86** [comment]
@lucasgomide e @carolcodes

Galaxy 5

![image](https://user-images.githubusercontent.com/1631477/50530909-b9a88e80-0ae9-11e9-82a2-e59c9e854e51.png)

**Comment by glaucia86** [comment]
@lucasgomide e @carolcodes

Pixel 2

![image](https://user-images.githubusercontent.com/1631477/50530915-cf1db880-0ae9-11e9-8cee-e99a99051a98.png)


Testado em todas as plataformas possíveis... aprovam ou não? Se sim... envio o PR para vcs! ;)

**Comment by glaucia86** [comment]
O que tá 'cagando' um pouco é a lista. O que posso fazer é mover a imagem um pouco mais para cima... aí ficaria da seguinte maneira:

**iPhone 6/7/8**

![image](https://user-images.githubusercontent.com/1631477/50530978-76025480-0aea-11e9-92c2-a64712b0b12b.png)


**Galaxy 5S**

![image](https://user-images.githubusercontent.com/1631477/50530982-86b2ca80-0aea-11e9-8286-03f9f5281be2.png)

**Pixel 2**

![image](https://user-images.githubusercontent.com/1631477/50530988-95997d00-0aea-11e9-9ff4-9fc32a799ffe.png)

Inclui o seguinte código na tag **img**

```
<img align="right" srcset="https://i.imgsafe.org/2c/2c024270b3.gif, https://i.imgsafe.org/2c/2c024270b3.gif 1.5x, https://i.imgsafe.org/2c/2c024270b3.gif 2x" src="https://i.imgsafe.org/2c/2c024270b3.gif" width="150px;" />
```

Seguindo o conceito da documentação do site do **Mozilla** sobre a propriedade da tag img: srset

https://developer.mozilla.org/pt-BR/docs/Aprender/HTML/Multimedia_and_embedding/Responsive_images

@lucasgomide e @carolcodes

**Comment by glaucia86** [comment]
Enviado o PR. Por favor... deem uma olhada e vejam se ficou melhor agora ;) 
@lucasgomide @carolcodes

**Comment by glaucia86** [comment]
Depois @lucasgomide  ... só altera a parte que está escrito errado no README.md

```suggestion
Agradecimentos especiais para Glaucia e Lucas que propuseram em nos ajudar com ótimas ideias e modificações
```

**Comment by lucasgomide** [comment]
Fique à vontade para fazer estas alterações @glaucia86 (:

**Comment by glaucia86** [comment]
> Fique à vontade para fazer estas alterações @glaucia86 (:

feito no PR #76

**Comment by lucasgomide** [comment]
@glaucia86 merged! Valeu (:
