### ISSUE TITLE
Incluir o canal - Sthefane Soares - Vida Programação

### ISSUE THREAD

**Issue by glaucia86** [carolcodes/youtube-br-desenvolvimento#75]
@lucasgomide a Sthepane reclamou comigo de que o canal dela não estava listado. E no último PR que fiz, estava..
Mas, de qq forma tou enviando as infos relacionados ao canal dela!

```
Sthefane Soares - Vida Programação - Canal que trata de programação e opinião própria sobre softwares. Para apaixonados por Tecnologia da Informação.
Tags: java,android, ionic, c#, sql

LINK: https://www.youtube.com/channel/UCcgvGfLMZ8Xh8lxhFPMqjLw

```

**Comment by lucasgomide** [comment]
@glaucia86 não entendi. O canal dela esta na lista sim.

**Comment by glaucia86** [comment]
Ahh blz. Agora que vi. Mas, coloca na parte de Desenvolvimento Mobile. ;)
Ela fala muito de Ionic e Android @lucasgomide
